apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: chat-service
        image: __ACR_LOGIN_SERVER__/chat-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: Mongo__ConnectionString
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_CONNECTION_ATLAS
        - name: Mongo__Database
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_DB_CHAT
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_CONNECTION
        - name: JwtSettings__RsaPublicKey
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_RSA_PUBLIC_KEY
        - name: FrontendUrl
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: FRONTEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
  - port: 8080
    targetPort: 8080


